accepted = [
    "Apache-2.0",
    "MIT",
    "0BSD",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
private = { ignore = true }
workarounds = ["ring"]

[option-ext]
accepted = ["MPL-2.0"]

[ring]
accepted = ["OpenSSL"]
