use super::*;
use poqi_db::ConnectionProfile;
use poqi_test_support::{should_run_integration_tests, start_postgres_container};

#[tokio::test]
async fn refresh_populates_tables() {
    if !should_run_integration_tests("poqi-catalog") {
        return;
    }

    let (_node, port) = start_postgres_container().await;
    let profile = ConnectionProfile::new(
        "catalog-test",
        format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres?sslmode=disable"),
    );

    let database = Database::new();
    database
        .connect(&profile)
        .await
        .expect("connect to postgres");
    prepare_catalog_fixture(&database).await;

    let mut catalog = Catalog::new(database.clone());
    catalog.refresh().await.expect("refresh catalog");

    assert_catalog_contents(&catalog);
    assert_limited_role_visibility(&database).await;
}

async fn prepare_catalog_fixture(database: &Database) {
    database
        .batch_execute(
            "CREATE SCHEMA catalog_demo;
             CREATE EXTENSION file_fdw;
             CREATE TABLE catalog_demo.widgets (
                 id SERIAL PRIMARY KEY,
                 name TEXT NOT NULL DEFAULT 'widget'
             );
             CREATE TABLE catalog_demo.widget_parts (
                 id SERIAL PRIMARY KEY,
                 widget_id INTEGER NOT NULL REFERENCES catalog_demo.widgets(id)
             );
             CREATE TABLE catalog_demo.composite_identity (
                 tenant_id INTEGER,
                 item_id INTEGER,
                 PRIMARY KEY (tenant_id, item_id)
             );
             CREATE TABLE catalog_demo.metrics (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 value INT NOT NULL,
                 doubled INT GENERATED ALWAYS AS (NULLIF(value, 0)) STORED
             );
             CREATE DOMAIN catalog_demo.required_text AS TEXT NOT NULL;
             CREATE TABLE catalog_demo.domain_holder (value catalog_demo.required_text);
             CREATE VIEW catalog_demo.widget_view AS SELECT id FROM catalog_demo.widgets;
             CREATE MATERIALIZED VIEW catalog_demo.widget_materialized AS
                 SELECT id, name FROM catalog_demo.widgets;
             CREATE SERVER catalog_demo_files FOREIGN DATA WRAPPER file_fdw;
             CREATE FOREIGN TABLE catalog_demo.foreign_metrics (id INTEGER, note TEXT)
                 SERVER catalog_demo_files
                 OPTIONS (filename '/tmp/poqi-catalog-foreign.csv', format 'csv');
             CREATE SCHEMA \"catalog.demo\";
             CREATE TABLE \"catalog.demo\".\"widget.parts\" (\"value.with.dot\" TEXT);
             CREATE ROLE catalog_limited;
             CREATE TABLE catalog_demo.visibility_delete (id INT, secret TEXT);
             CREATE TABLE catalog_demo.visibility_columns (allowed TEXT, hidden TEXT);
             CREATE MATERIALIZED VIEW catalog_demo.visibility_hidden AS SELECT 1 AS id;
             GRANT USAGE ON SCHEMA catalog_demo TO catalog_limited;
             GRANT DELETE ON catalog_demo.visibility_delete TO catalog_limited;
             GRANT SELECT (allowed) ON catalog_demo.visibility_columns TO catalog_limited;",
        )
        .await
        .expect("create demo objects");
}

fn assert_catalog_contents(catalog: &Catalog) {
    let relations: Vec<_> = catalog.tables().map(TableMeta::relation).collect();
    assert!(relations.contains(&QualifiedRelation::in_schema("catalog_demo", "widgets")));
    assert!(relations.contains(&QualifiedRelation::in_schema("catalog_demo", "widget_view")));
    assert!(relations.contains(&QualifiedRelation::in_schema(
        "catalog.demo",
        "widget.parts"
    )));

    assert_relation_kinds(catalog);

    let columns: Vec<_> = catalog
        .columns()
        .map(|column| format!("{}.{}.{}", column.schema, column.table, column.name))
        .collect();
    assert!(columns.contains(&"catalog_demo.widgets.id".to_string()));
    assert!(columns.contains(&"catalog_demo.widget_materialized.name".to_string()));
    assert!(columns.contains(&"catalog_demo.foreign_metrics.note".to_string()));
    assert!(columns.contains(&"catalog.demo.widget.parts.value.with.dot".to_string()));

    let composite_primary_key = catalog
        .columns()
        .filter(|column| column.table == "composite_identity" && column.is_primary_key)
        .map(|column| column.name.as_str())
        .collect::<Vec<_>>();
    assert_eq!(composite_primary_key, vec!["tenant_id", "item_id"]);

    let id_column = catalog
        .columns()
        .find(|column| {
            column.schema == "catalog_demo" && column.table == "widgets" && column.name == "id"
        })
        .expect("id column present");
    assert!(id_column.is_primary_key);
    assert_eq!(id_column.nullability, Nullability::NotNull);
    assert_eq!(id_column.default_kind, ColumnDefault::Default);
    assert!(!id_column.is_foreign_key);
    assert!(id_column.character_maximum_length.is_none());

    let widget_fk = catalog
        .columns()
        .find(|column| {
            column.schema == "catalog_demo"
                && column.table == "widget_parts"
                && column.name == "widget_id"
        })
        .expect("widget_parts.widget_id column present");
    assert!(widget_fk.is_foreign_key);
    assert!(!widget_fk.is_primary_key);
    assert_eq!(widget_fk.default_kind, ColumnDefault::None);
    assert_eq!(widget_fk.nullability, Nullability::NotNull);

    let identity_column = catalog
        .columns()
        .find(|column| {
            column.schema == "catalog_demo" && column.table == "metrics" && column.name == "id"
        })
        .expect("metrics.id column present");
    assert!(identity_column.is_primary_key);
    assert_eq!(identity_column.default_kind, ColumnDefault::Identity);
    assert_eq!(identity_column.nullability, Nullability::NotNull);

    let generated_column = catalog
        .columns()
        .find(|column| {
            column.schema == "catalog_demo" && column.table == "metrics" && column.name == "doubled"
        })
        .expect("metrics.doubled column present");
    assert_eq!(generated_column.default_kind, ColumnDefault::Generated);
    assert_eq!(generated_column.nullability, Nullability::Nullable);

    let domain_column = catalog
        .columns()
        .find(|column| column.schema == "catalog_demo" && column.table == "domain_holder")
        .expect("domain-backed column present");
    assert_eq!(domain_column.nullability, Nullability::NotNull);

    let snapshot = catalog.snapshot();
    let fk_entry = snapshot
        .foreign_keys
        .iter()
        .find(|fk| {
            fk.schema == "catalog_demo" && fk.table == "widget_parts" && fk.column == "widget_id"
        })
        .expect("fk metadata present");
    assert_eq!(fk_entry.referenced_table, "widgets");
    assert_eq!(fk_entry.referenced_column, "id");
}

async fn assert_limited_role_visibility(database: &Database) {
    database
        .batch_execute("SET ROLE catalog_limited")
        .await
        .expect("assume limited catalog role");
    let mut limited = Catalog::new(database.clone());
    limited.refresh().await.expect("refresh as limited role");
    database
        .batch_execute("RESET ROLE")
        .await
        .expect("restore catalog owner role");

    assert!(limited
        .tables()
        .any(|table| table.name == "visibility_delete"));
    assert!(limited
        .tables()
        .any(|table| table.name == "visibility_columns"));
    assert!(!limited
        .tables()
        .any(|table| table.name == "visibility_hidden"));
    assert!(!limited
        .columns()
        .any(|column| column.table == "visibility_delete"));
    let visible_columns = limited
        .columns()
        .filter(|column| column.table == "visibility_columns")
        .map(|column| column.name.as_str())
        .collect::<Vec<_>>();
    assert_eq!(visible_columns, vec!["allowed"]);
}

fn assert_relation_kinds(catalog: &Catalog) {
    let widgets = catalog
        .tables()
        .find(|table| table.schema == "catalog_demo" && table.name == "widgets")
        .expect("widgets relation metadata");
    assert_eq!(widgets.relation_kind, RelationKind::Table);
    assert!(widgets.relation_kind.supports_row_identity());

    let widget_view = catalog
        .tables()
        .find(|table| table.schema == "catalog_demo" && table.name == "widget_view")
        .expect("widget view relation metadata");
    assert_eq!(widget_view.relation_kind, RelationKind::View);
    assert!(!widget_view.relation_kind.supports_row_identity());

    let materialized = catalog
        .tables()
        .find(|table| table.name == "widget_materialized")
        .expect("materialized view relation metadata");
    assert_eq!(materialized.relation_kind, RelationKind::MaterializedView);
    assert!(!materialized.relation_kind.supports_row_identity());

    let foreign = catalog
        .tables()
        .find(|table| table.name == "foreign_metrics")
        .expect("foreign table relation metadata");
    assert_eq!(foreign.relation_kind, RelationKind::ForeignTable);
    assert!(!foreign.relation_kind.supports_row_identity());
}

#[test]
fn qualified_relation_quotes_components_without_losing_boundaries() {
    let relation = QualifiedRelation::in_schema("schema.with.dot", "table\"with.dot");
    assert_eq!(
        relation.quoted(),
        "\"schema.with.dot\".\"table\"\"with.dot\""
    );
    assert_eq!(relation.display_name(), relation.quoted());

    let unqualified = QualifiedRelation::unqualified("Mixed.Name");
    assert_eq!(unqualified.quoted(), "\"Mixed.Name\"");
}

#[test]
fn primary_key_query_joins_constraints_to_their_own_table() {
    assert!(PRIMARY_KEYS_QUERY.contains("kc.table_catalog = tc.table_catalog"));
    assert!(PRIMARY_KEYS_QUERY.contains("kc.table_name = tc.table_name"));
}

#[test]
fn schema_table_map_groups_and_sorts() {
    let snapshot = CatalogSnapshot {
        tables: vec![
            TableMeta {
                id: TableId("public.b".into()),
                name: "b".into(),
                schema: "public".into(),
                relation_kind: RelationKind::Table,
            },
            TableMeta {
                id: TableId("public.a".into()),
                name: "a".into(),
                schema: "public".into(),
                relation_kind: RelationKind::Table,
            },
            TableMeta {
                id: TableId("other.x".into()),
                name: "x".into(),
                schema: "other".into(),
                relation_kind: RelationKind::Table,
            },
        ],
        columns: Vec::new(),
        foreign_keys: Vec::new(),
    };

    let map = schema_table_map(&snapshot);
    assert_eq!(map.get("public"), Some(&vec!["a".into(), "b".into()]));
    assert_eq!(map.get("other"), Some(&vec!["x".into()]));
}
