[package]
name = "poqi-search-semantic"
version = "1.0.0"
edition = "2021"
license-file.workspace = true

[dependencies]
anyhow = { workspace = true }
ndarray = { workspace = true }
num_cpus = { workspace = true }
ort = { workspace = true }
parking_lot = { workspace = true }
tokenizers = { workspace = true }
tracing = { workspace = true }


[lints]
workspace = true
