[package]
name = "poqi-db"
version = "1.0.0"
publish = false
edition = "2021"
license-file.workspace = true

[dependencies]
thiserror = { workspace = true }
deadpool-postgres = { version = "0.12", features = ["rt_tokio_1"] }
tokio-postgres = { version = "0.7" }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
futures = { workspace = true }
tokio-postgres-rustls = "0.13"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12", "ring"] }
rustls-native-certs = "0.8"
url = { workspace = true }

[dev-dependencies]
rcgen = "0.14"
tokio = { workspace = true }
poqi-test-support = { path = "../tools/test-support" }


[lints]
workspace = true
